version: "3.9"
services:
    backend:
        image: online_shopping_backend
        build:
            context: .
            dockerfile: backend.Dockerfile
        volumes:
            - ./backend:/app/backend
            - /app/backend/node_modules
        environment:
            - PORT=5000
            - HOST=0.0.0.0
        command: yarn dev
        ports:
            - "5000:5000"
    react-app:
        image: online_shopping_react
        build:
            context: .
            dockerfile: react.Dockerfile
        volumes:
            - ./react-app:/app/react-app
            - /app/react-app/node_modules
        environment:
            - PORT=8080
            - VITE_BACKEND_URL=http://localhost:5000
        ports:
            - "8080:8080"
